site_name: "Отчеты по лабораторным работам - Цырульников Артем"
site_url: https://tlartem.github.io/TonikX-ITMO_ICT_WebDevelopment_2025-2026/
docs_dir: pages

nav:
  - Главная: index.md
  - Лабораторная работа 1: lab1.md

theme:
  name: material

markdown_extensions:
  - codehilite
  - tables
  - toc:
      permalink: true

plugins:
  - search